### ISSUE TITLE
Feature request: Make `import_map` an optional string field

### ISSUE THREAD

**Issue by nnmrts** [Tricked-dev/diplo#5]
Currently one can only decide between absolutely no import map or diplo using an import map under `./diplo/import_map.json`.

Would be nice if this setting would just be a string, so one can set the path of the import map on their own, like with the deno `--import-map` flag.

**Comment by Tricked-dev** [comment]
You can just append the import map normally 
```toml
[scripts]
start = "deno run --import-map=imports.json mod.ts"

``` 
that will break if you enable the import map feature though
